### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Mugens** [Mugens/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by vlad-herasymchuk** [comment]
<section>
                  <h3>ACHIEVEMENTS 🏆</h3>
                  <ul>
                    <li>#1 🥇 in <strong><a href="https://www.ign.com/articles/2009/02/18/top-25-street-fighters-the-final-five">"Top 25 Street Fighter Characters"</a></strong>  by IGN, who also called me "fancy", "icon" and "a testament to the virtue of simplicity" ❤️</li>
                    <li>#2 🥈 in "Top 20 Street Fighter Characters of All Time" by GameDaily, same council found me worth of #6 place in "Top 25 Capcom Characters of All Time", which I proudly share with my partner Ken</li>
                    <li>I was named <strong><a href="https://screenrant.com/most-powerful-street-fighter-characters/">"5th Most Powerful Street Fighter Character"</a></strong>  by Screen Rant-san</li>
                    <li>#71 in "Top 100 Heroes of All Time" by UGO Networks, also recognized #2 in their list of "Top 50 Street Fighter Characters"</li>
                    <li>In a survey of 4000 online matches for Super Street Fighter IV, I got to be the most popular character, with 16.6% of players choosing my side 🥋</li>
                  </ul>
                </section>
                <section>
                  <h3>LIFE 🏡 & EDUCATION 🏫</h3>
                  <p>To live is to fight and to fight is to live. I started learning fighting at my master Gouken's castle, I was beaten at head way too often to remember when exactly.</p>
                </section>
                <section>
                  <h3>Languages 🎌</h3>
                  <p class="tags small">
                    <a href="/jp-jp" hreflang="jp" rel="alternate" class="language" lang="jp">🇯🇵 JAPANESE</a>
                    <a href="/cn-cn" hreflang="🇨🇳" rel="alternate" class="language" lang="🇨🇳">🇨🇳 MANDARIN</a>
                      <span class="language" lang="en">🇺🇸 ENGLISH</span></p>
                </section>
                <section>
                  <h3>Skills ⚙️</h3>
                  <p class="tags small">KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS</p>
                </section>
                <section>
                  <h3>Character 👽</h3>
                  <p class="tags small">NOBLE DIRECT BOLD CONFIDENT DARING 
                    <span class="schizophrenic">SCHIZOPHRENIC</span>
                    DRAMATIC PERSUASIVE IMMEDIATE WISE
                  </p>
                </section>
                <section>
                  <h3>Likes&#x1f603;</h3>
                 <p class="tags small" > GI VEGETABLES🥕 BLOOD SMALL MARSHMELLOWS 
                   <button id="red" class="color red">RED COLOR</button>
                     KILLED ENEMY
                  </p>
                </section>
                <section>
                  <h3>Dislikes&#x1f61e;</h3>
                  <p class="tags small">BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES</p>
                </section>
                <section>
                  <h3>Wants&#x1f97a;</h3>
                  <p class="tags small bulleted"><span class="tag">BE FIT</span><span class="tag">WRITE MORE BOOKS</span><span class="tag">FIND A GIRLFRIEND TO GO TO CINEMA WITH</span><span class="tag">KILL ALL OF AKUMA FAMILY</span></p>
                </section>
